/*
 * OpenAPI servizi ad uso solo interno
 * API accessibili solo da microservizi interni
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pn@pagopa.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.pagopa.pn.timelineservice.dto.ext.notification;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Politica di addebitamento dei costi di notifica. &lt;br/&gt; - _FLAT_RATE_: costo forfettario fisso. In questa modalità SEND non gestisce  il costo della notifica per il destinatario.&lt;br/&gt; - _DELIVERY_MODE_: costo calcolato in base all&#39;effettivo percorso di notifica. &lt;br/&gt;
 */
public enum NotificationFeePolicy {
  
  FLAT_RATE("FLAT_RATE"),
  
  DELIVERY_MODE("DELIVERY_MODE");

  private String value;

  NotificationFeePolicy(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static NotificationFeePolicy fromValue(String value) {
    for (NotificationFeePolicy b : NotificationFeePolicy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

