package it.pagopa.pn.timelineservice.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class PnTimelineServiceExceptionCodes extends PnExceptionsCodes {

    public static final String ERROR_CODE_TIMELINESERVICE_STATUSNOTFOUND = "PN_TIMELINESERVICE_STATUSNOTFOUND";
    public static final String ERROR_CODE_TIMELINESERVICE_ADDTIMELINEFAILED = "PN_TIMELINESERVICE_ADDTIMELINEFAILED";
    public static final String ERROR_CODE_TIMELINESERVICE_NOTIFICATIONSTATUSFAILED = "PN_TIMELINESERVICE_NOTIFICATION_STATUS_FAILED";
    public static final String ERROR_CODE_TIMELINESERVICE_DUPLICATED_ITEM = "PN_TIMELINESERVICE_DUPLICATED_ITEM";
    public static final String ERROR_CODE_TIMELINESERVICE_TIMELINE_ELEMENT_NOT_PRESENT = "ERROR_CODE_TIMELINESERVICE_TIMELINEELEMENTNOTPRESENT";

}
